version: '3.8'
services:
  api:
    build: 
      dockerfile: ./api/Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
        DATABASE_URL: postgres://admin:secret@postgres:5432/db
        NODE_ENV: dev
        PORT: 3000
    ports:
      - "8080:3000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    ports:
      - '35000:5432'
